modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU LGPL 3.0"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId = "thornythorns"
version = "1.0.0"
displayName = "ThornyThorns"
updateJSONURL = "https://to-be-filled.io/url.json"
displayURL="http://example.com/"
logoFile="thornythorns.png"
authors = "PugzAreCute"
description = '''
Make thorns reduce damage from throny sources
'''
[[dependencies.thornythorns]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.thornythorns]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
